# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azdevops&tabs=yaml

jobs:
- job: 'Test'

  strategy:
    matrix:
#       linux-py36:
#         imageName: 'ubuntu-16.04'
#         python.version: '3.6'
#       mac-py36:
#         imageName: 'macos-10.13'
#         python.version: '3.6'
      windows-py36:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
        oiio.tag: 'Release-2.0.4'
    # maxParallel: 3

  pool:
    vmImage: $(imageName)


  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      git clone https://github.com/OpenImageIO/oiio.git
      cd oiio
      git fetch --all --tags --prune
      git checkout tags/$(oiio.tag)
    displayName: Download oiio-$(oiio.tag)

  # Linux
  - bash: |
      export IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get IP on Linux

  # macOS
  - bash: |
      export IPADDR=$(ifconfig | grep 'en0' -A3 | tail -n1 | awk '{print $2}')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Get IP on macOS

  # Windows
  - powershell: |
      cd C:/ 
      git clone https://github.com/Microsoft/vcpkg.git 
      cd vcpkg 
      .\bootstrap-vcpkg.bat 
      .\vcpkg integrate install
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install the Microsoft "vcpkg" manager
  - powershell: |
      cd C:/vcpkg
      .\vcpkg list
      .\vcpkg install boost
      .\vcpkg list
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Install vcpkg prerequisites


#   # now we use the value, no matter where we got it
#   - script: |
#       echo The IP address is $(IP_ADDR)
      
#   # also test python
#   - script: |
#       python --version
  
