# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting

jobs:
- job: 'Test'

  strategy:
    matrix:
      linux-py36:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      mac-py36:
        imageName: 'macos-10.13'
        python.version: '3.6'
      windows-py36:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
    # maxParallel: 3

  pool:
    vmImage: $(imageName)


  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  # Linux
  - bash: |
      export IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Get IP on Linux
  # macOS
  - bash: |
      export IPADDR=$(ifconfig | grep 'en0' -A3 | tail -n1 | awk '{print $2}')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Get IP on macOS
  # Windows
  - powershell: |
      Set-Variable -Name IPADDR -Value ((Get-NetIPAddress | ?{ $_.AddressFamily -eq "IPv4" -and !($_.IPAddress -match "169") -and !($_.IPaddress -match "127") } | Select-Object -First 1).IPAddress)
      Write-Host "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Get IP on Windows

  # now we use the value, no matter where we got it
  - script: |
      echo The IP address is $(IP_ADDR)
