# https://aka.ms/yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/cross-platform-scripting
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azdevops&tabs=yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azdevops&tabs=yaml
# https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md

jobs:
- job: 'oiio'

  strategy:
    matrix:
      ubuntu-py36:
        python.version: '3.6'
    #   windows-py37:
    #     python.version: '3.7'
    # maxParallel: 3

  variables:
    azure.vm_image: 'ubuntu-16.04'
    oiio.ref: 'bb2c617e83b3b264c9f4b7503d3c01c16570fdb7'
    oiio.head_ref: 'master'
    oiio.sha512: '5c198bd53ebc84847df3f8c40c0eedcb16d9e45ad9627d2e69faa44ba0966f74cac29cb3e93af5df7162ef4af82101770118e10695e25b287d05d499932fab0f'
    pypackage.version: '2.0.4-$(BuildID)'
    pypackage.os_name: 'Microsoft :: Linux'

  pool:
    vmImage: $(azure.vm_image)


  steps:

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azdevops
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      addToPath: true

  # Make setup.py ready
  - bash: |
      echo "to do"
