# Build openimageio for python

on:
  push:

  workflow_dispatch:


jobs:

  linux:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    # Build oiio
    - name: Build oiio
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install libjpeg-dev
        sudo apt-get install zlib1g-dev
        sudo apt-get install libpng-dev
        sudo apt-get install libtiff-dev
        sudo apt-get install libopenexr-dev
        sudo apt-get install libraw-dev
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -y
        sudo apt-get install g++-7 -y
        git clone https://github.com/OpenImageIO/oiio.git        
        pip3 install "pybind11[global]"
        pip3 install numpy
        cd oiio
        git checkout v2.2.10.0
        mkdir build
        cd build
        export CFLAGS=-Werror=unused-variable
        export CXXFLAGS=-Werror=unused-variable
        cmake .. -DCMAKE_CXX_FLAGS="-Wno-error=unused-variable"
        gcc --version
        make VERBOSE=1 STOP_ON_WARNING=0
      shell: bash
      env:
        OIIO_PYTHON_VERSION: "3.7"

    - name: Inject variable values into setup.py
      run: |
        cd src/python
        sed -i'' 's/PACKAGE_VERSION/2.2.10.0/g' setup.py
        sed -i'' 's/PYTHON_VERSION/3.7.9/g' setup.py
        sed -i'' 's/OS_NAME/Microsoft :: POSIX :: Linux/g' setup.py
        cat setup.py

    - name: Show contents
      run: |
        ls -lah
        cd oiio
        echo "oiio"
        ls -lah
        cd build
        echo "oiio/build"
        ls -lah 
        echo "oiio/ext"
        cd ../ext
        ls -lah 
        echo "oiio/build/lib"
        cd ../build/lib
        ls -lah
        cd dist
        echo "oiio/build/dist"
        ls -lah
      shell: bash
    - name: Copy files into oiio Python package
      run: |
        cp oiio/dist/lib/python3.7/site-packages/*.so src/python/oiio
    - name: Build wheel
      run: |
        mkdir dist
        export DIST_DIR="$(PWD)/dist"
        cd src/python
        python3.7 -m pip install -U pip
        pip3.7 install -U setuptools wheel
        python3 setup.py bdist_wheel --python-tag=37 --plat-name=linux_x86_64 --dist-dir="$DIST_DIR"
        cd $DIST_DIR
        ls -lah

      
